# Generated by Django 5.1.1 on 2024-10-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('physical_activity', models.TextField(blank=True, null=True)),
                ('psychological_assessment', models.TextField(blank=True, null=True)),
                ('drugs_alcohol', models.TextField(blank=True, null=True)),
                ('medical_condition', models.TextField(blank=True, null=True)),
                ('injury_illness', models.TextField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('treatment_surgery', models.TextField(blank=True, null=True)),
                ('current_medication', models.TextField(blank=True, null=True)),
                ('allergy', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
