# Generated by Django 5.1.1 on 2024-11-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('physical_activity', models.CharField(choices=[('NONE', 'None'), ('ONE_TO_THREE_DAYS', 'One to Three Days'), ('THREE_OR_MORE', 'Three or More Days')], max_length=250, null=True)),
                ('psychological_assessment', models.CharField(choices=[('NONE', 'None'), ('OBSESSIVE_COMPULSIVE_DISORDER', 'Obsessive-compulsive Disorder'), ('PANIC_DISORDER', 'Panic Disorder'), ('SOCIAL_ANXIETY_DISORDER', 'Social Anxiety Disorder'), ('BIPOLAR_DISORDER', 'Bipolar Disorder'), ('SCHIZOID_PERSONALITY_DISORDER', 'Schizoid Personality Disorder'), ('BINGE_EATING_DISORDER', 'Binge Eating Disorder'), ('PICA', 'Pica'), ('OTHER', 'Other')], max_length=500, null=True)),
                ('drugs_alcohol', models.CharField(choices=[('NONE', 'None'), ('ALCOHOL', 'Alcohol'), ('CANNABIS', 'Cannabis'), ('COCAINE', 'Cocaine'), ('FENTANYL', 'Fentanyl'), ('HALLUCINOGINS', 'Hallucinogens'), ('HEROIN', 'Heroin'), ('KETAMINE', 'Ketamine'), ('METHAMPHETAMINE', 'Methamphetamine'), ('OXYCONTIN', 'Oxycontin'), ('TOBACCO', 'Tobacco'), ('OTHER', 'Other')], max_length=500, null=True)),
                ('medical_condition', models.CharField(choices=[('NONE', 'None'), ('E78.5', 'Hyperlipidemia'), ('M54.5', 'Low back pain'), ('K21.9', 'Gastroesophageal reflux disorder'), ('N39.0', 'Urinary tract infection'), ('R07', 'Chest pain'), ('E03.9', 'Hypothyroidism'), ('J20.9', 'Acute bronchitis'), ('E11.9', 'Type II diabetes mellitus without complications'), ('M709.609', 'Pain in unspecified limb'), ('OTHER', 'Other')], max_length=1000, null=True)),
                ('injury_illness', models.CharField(choices=[('NONE', 'None'), ('SPRAIN_STRAIN', 'Sprain/strain'), ('KNEE_INJURY', 'Knee injury'), ('SWOLLEN_MUSCLES', 'Swollen muscles'), ('ACHILLES_INJURY', 'Achilles injury'), ('ROTATOR_CUFF_INJURY', 'Rotator cuff injury'), ('FRACTURE', 'fracture'), ('DISLOCATION', 'Dislocation'), ('OTHER', 'Other')], max_length=750, null=True)),
                ('family_history', models.CharField(choices=[('NONE', 'None'), ('HEART_DISEASE', 'Heart disease'), ('DIABETES', 'Diabetes'), ('KIDNEY_DISEASE', 'Kidney disease'), ('BLEEDING_DISEASE', 'Bleeding disease'), ('LUNG_DISEASE', 'Lung disease'), ('HIGH_BLOOD_PRESSURE', 'High blood pressure'), ('HIGH_CHOLESTEROL', 'High cholesterol'), ('ASTHMA', 'Asthma'), ('CANCER', 'Cancer'), ('STROKE', 'Stroke'), ('ALZHEIMERS_DEMENTIA', "Alzheimer's/Dementia"), ('OTHER', 'Other')], max_length=500, null=True)),
                ('treatment_surgery', models.CharField(choices=[('NONE', 'None'), ('APPENDECTOMY', 'Appendectomy'), ('BREAST_BIOPSY', 'Breast biopsy'), ('CATARACT_SURGERY', 'Cataract surgery'), ('CESAREAN_SECTION', 'Cesarean section'), ('CORONARY_ARTERTY_BYPASS', 'Coronary artery bypass'), ('HYSTERECTOMY', 'Hysterectomy'), ('LOW_BACK_PAIN_SURGERY', 'Low back pain surgery'), ('MASTECTOMY', 'Mastectomy'), ('PROSTECTOMY', 'Prostectomy'), ('OTHER', 'Other')], max_length=750, null=True)),
                ('current_medication', models.CharField(choices=[('NONE', 'None'), ('ATORVASTATIN', 'Atorvastatin'), ('METFORMIN', 'Metformin'), ('LISINOPRIL', 'Lisinopril'), ('LEVOTHROXINE', 'Levothroxine'), ('AMLODIPINE', 'Amlodipine'), ('METOPROLOL', 'Metoprolol'), ('ALBUTEROL', 'Albuterol'), ('OTHER', 'Other')], max_length=250, null=True)),
                ('allergy', models.CharField(choices=[('NONE', 'None'), ('FISH', 'Fish'), ('SHELLFISH', 'Shellfish'), ('TREE_NUTS', 'Tree nuts'), ('PEANUTS', 'Peanuts'), ('DAIRY', 'Dairy'), ('EGGS', 'Eggs'), ('ANTIBIOTICS', 'Antibiotics'), ('ASPIRIN', 'Aspirin'), ('CHEMOTHERAPY_MEDICATIONS', 'Chemotherapy medications'), ('ANTICONVULSANTS', 'Anticonvulsants'), ('OTHER', 'Other')], max_length=250, null=True)),
                ('side_effects', models.CharField(choices=[('NONE', 'None'), ('NAUSEA', 'Nausea'), ('SKIN_IRRITATION', 'Skin irritation'), ('DRY_MOUTH', 'Dry mouth'), ('DROWSINESS', 'Drowsiness'), ('OTHER', 'Other')], max_length=250, null=True)),
            ],
        ),
    ]
