# Generated by Django 5.1.1 on 2024-11-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_alter_medicalrecord_physical_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='medical_condition',
            field=models.CharField(choices=[('None', 'None'), ('Hyperlipidemia', 'E78 5'), ('Low back pain', 'M54 5'), ('Gastroesophageal reflux disorder', 'K21 9'), ('Urinary tract infection', 'N39 0'), ('Chest pain', 'R07 9'), ('Hypothyroidism', 'E03 9'), ('Acute bronchitis', 'J20 9'), ('Type II diabetes mellitus without complications', 'E11 9'), ('Pain in unspecified limb', 'M709 609'), ('Other', 'Other')], max_length=1000, null=True),
        ),
    ]
