# Generated by Django 5.1.1 on 2024-11-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_alter_medicalrecord_medical_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='medical_condition',
            field=models.CharField(choices=[('None', 'None'), ('Hyperlipidemia', 'Hyperlipidemia'), ('Low back pain', 'Low Back Pain'), ('Gastroesophageal reflux disorder', 'Gastroesophageal Reflux Disorder'), ('Urinary tract infection', 'Urinary Tract Infection'), ('Chest pain', 'Chest Pain'), ('Hypothyroidism', 'Hypothyroidism'), ('Acute bronchitis', 'Acute Bronchitis'), ('Type II diabetes mellitus without complications', 'Type Ii Diabetes Mellitus Without Complications'), ('Pain in unspecified limb', 'Pain In Unspecified Limb'), ('Other', 'Other')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='physical_activity',
            field=models.CharField(choices=[('NONE', 'None'), ('ONE_TO_THREE_DAYS', 'One to Three Days'), ('THREE_OR_MORE_DAYS', 'Three or More Days')], max_length=251, null=True),
        ),
    ]
