# Generated by Django 5.1.1 on 2024-11-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0006_alter_medicalrecord_medical_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='medical_condition',
            field=models.CharField(choices=[('NONE', 'None'), ('HYPERLIPIDEMIA', 'Hyperlipidemia'), ('LOW_BACK_PAIN', 'Low Back Pain'), ('GASTROESOPHAGEAL_REFLUX_DISORDER', 'Gastroesophageal Reflux Disorder'), ('URINARY_TRACT_INFECTION', 'Urinary Tract Infection'), ('CHEST_PAIN', 'Chest Pain'), ('HYPOTHYROIDISM', 'Hypothyroidism'), ('ACUTE_BRONCHITIS', 'Acute Bronchitis'), ('TYPE_II_DIABETES_MELLITUS_WITHOUT_COMPLICATIONS', 'Type II Diabetes Mellitus Without Complications'), ('PAIN_IN_UNSPECIFIED_LIMB', 'Pain in Unspecified Limb'), ('OTHER', 'Other')], max_length=1000, null=True),
        ),
    ]
