services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000" # Backend runs on port 8000
    environment:
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"
      DJANGO_SUPERUSER_PASSWORD: "admin123"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ALLOWED_HOSTS: "localhost,127.0.0.1,django_backend,react_frontend,184.72.127.33,184.72.127.33:8000"
    restart: always

  frontend:
    build:
      context: ./frontend/virtue-health
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "80:80" # Frontend uses port 80
    restart: always
