# Generated by Django 5.1.1 on 2024-09-27 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_dashboard', '0001_initial'),
        ('patient_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record_detail', to='patient_portal.patient'),
        ),
    ]
