# Generated by Django 5.1.1 on 2024-09-29 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_doctor_alter_appointment_patient'),
        ('doctor_dashboard', '0004_remove_doctor_user'),
        ('user', '0002_doctor_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record_detail', to='user.patient'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
