# Generated by Django 5.1.1 on 2024-10-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(choices=[('CHRONIC_CARE', 'chronic care'), ('PREVENTATIVE_CARE', 'preventative care'), ('SURGICAL_POST_OP ', 'surgical post-op')], default='PREVENTATIVE_CARE', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('CANCELED', 'canceled')], default='PENDING', max_length=10),
        ),
    ]
