# Generated by Django 5.1.1 on 2024-10-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_doctor_appointment_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(choices=[('CHRONIC_CARE', 'chronic care'), ('PREVENTATIVE_CARE', 'preventative care'), ('SURGICAL_POST_OP ', 'surgical post-op'), ('OTHER', 'other')], default='OTHER', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('CANCELED', 'canceled')], default='PENDING', max_length=10, null=True),
        ),
    ]
