# Generated by Django 5.1.1 on 2024-10-06 04:19

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_doctorprofile_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=datetime.date(2024, 10, 6), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
