# Generated by Django 5.1.1 on 2024-10-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_doctorprofile_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
