# Generated by Django 5.1.1 on 2024-10-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_patientprofile_ethnicity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='insurance_provider',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_provider',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(choices=[('GENERAL_DOCTOR', 'general doctor'), ('CARDIOLOGIST', 'cardiologist'), ('ORTHOPEDIST', 'orthopedist'), ('NEUROLIGIST', 'neurologist'), ('PSYCHIATRIST', 'psychiatrist'), ('PEDIATRICIAON', 'pediatrician')], max_length=100, null=True),
        ),
    ]
