# Generated by Django 5.1.1 on 2024-10-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_doctorprofile_insurance_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='patient_id',
        ),
    ]
