# Generated by Django 5.1.1 on 2024-10-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_patientprofile_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='user',
            new_name='user_id',
        ),
    ]
