# Generated by Django 5.1.1 on 2024-10-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='doctor_id',
        ),
    ]
