# Generated by Django 5.1.1 on 2024-10-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_user_doctorprofile_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
