# Generated by Django 5.1.1 on 2024-10-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_rename_user_id_doctorprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='img_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='img_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
