# Generated by Django 5.1.1 on 2024-10-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_patientprofile_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='race_ethnicity',
            field=models.CharField(blank=True, choices=[('WHITE', 'White (not of Hispanic origin)'), ('BLACK', 'Black (not of Hispanic origin)'), ('HISPANIC_LATINO', 'Hispanic or Latino'), ('ASIAN', 'Asian'), ('AMERICAN_INDIAN_NATIVE_ALASKAN', 'American Indian or Alaska Native'), ('NATIVE_HAWAIIAN_PACIFIC_ISLANDER', 'Native Hawaiian or Pacific Islander')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('DOCTOR', 'doctor'), ('PATIENT', 'patient')], max_length=150),
        ),
    ]
