# Generated by Django 5.1.1 on 2024-09-29 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_doctor_alter_appointment_patient'),
        ('doctor_dashboard', '0005_alter_medicalrecord_patient_delete_doctor'),
        ('lab_tests', '0002_alter_labtest_patient'),
        ('patient_portal', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
