# Generated by Django 5.1.1 on 2024-10-06 04:25

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_doctorprofile_id_remove_patientprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=datetime.datetime.now, null=True, size=None),
        ),
    ]
