# Generated by Django 5.1.1 on 2024-10-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0002_labtest_description_alter_labtest_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='lab_document',
            field=models.FileField(upload_to=''),
        ),
    ]
