# Generated by Django 5.1.1 on 2024-10-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0005_alter_labtest_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='test_type',
            field=models.CharField(choices=[('BLOOD', 'blood test'), ('FECAL', 'fecal'), ('SEMEN', 'semen'), ('TUMOR_MARKERS', 'tumor markers'), ('URINE', 'urine test')], max_length=100, null=True),
        ),
    ]
